theme: minima
title: Zach Oster's GitHub Page
author: Zach Oster
email: zach dot oster at g mail dot com
description: > # this means to ignore newlines until "baseurl:"
  Zach Oster's GitHub Page.

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  zach-oster # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
